## Hybrid Search Introduction and ChromaDB
  - Keyword search and Vector Search

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
#Sample documents
documents = [
    "This is a list which is containing sample documents",
    "Keywords are important for keyword-based search",
    "Document analysis involves extracting keywords",
    "Keyword-Based search relies on sparse embeddings"
]

In [ ]:
query="Keyword-based search"

In [ ]:
import re
def preprocess_text(text):
  text=text.lower()
  text=re.sub(r'[^\w\s]','',text)
  return text

In [ ]:
preprocess_documents = [preprocess_text(doc) for doc in documents]

In [ ]:
preprocess_documents

['this is a list which is containing sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [ ]:
print("Preprocessed Documents:")
for doc in preprocess_documents:
  print(doc)

Preprocessed Documents:
this is a list which is containing sample documents
keywords are important for keywordbased search
document analysis involves extracting keywords
keywordbased search relies on sparse embeddings


In [ ]:
print("Preprocessed Query:")
print(query)

Preprocessed Query:
Keyword-based search


In [ ]:
preprocess_query=preprocess_text(query)

In [ ]:
print("Preprocessed Query:")
print(preprocess_query)

Preprocessed Query:
keywordbased search


In [ ]:
vector=TfidfVectorizer()

In [ ]:
vector1 = vector.fit_transform(preprocess_documents)

In [ ]:
vector1

<4x21 sparse matrix of type '<class 'numpy.float64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [ ]:
vector1.toarray()

array([[0.        , 0.        , 0.31622777, 0.        , 0.31622777,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.63245553, 0.        , 0.        , 0.31622777, 0.        ,
        0.        , 0.31622777, 0.        , 0.        , 0.31622777,
        0.31622777],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [ ]:
vector1.toarray()[0]

array([0.        , 0.        , 0.31622777, 0.        , 0.31622777,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.63245553, 0.        , 0.        , 0.31622777, 0.        ,
       0.        , 0.31622777, 0.        , 0.        , 0.31622777,
       0.31622777])

In [ ]:
query1=vector.transform([preprocess_query])

In [ ]:
query1

<1x21 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [ ]:
query1.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ]])

In [ ]:
similarities = cosine_similarity(vector1,query1)

In [ ]:
similarities

array([[0.        ],
       [0.50551777],
       [0.        ],
       [0.48693426]])

In [ ]:
#Ranking
rank_indices=np.argsort(similarities,axis=0)[::-1].flatten()

In [ ]:
rank_indices

array([1, 3, 2, 0])

In [ ]:
ranked_documents=[documents[i] for i in rank_indices]

In [ ]:
ranked_documents

['Keywords are important for keyword-based search',
 'Keyword-Based search relies on sparse embeddings',
 'Document analysis involves extracting keywords',
 'This is a list which is containing sample documents']

In [ ]:
#output ranked documents
for i,doc in enumerate(ranked_documents):
  print(f"Rank{i+1}:{doc}")

Rank1:Keywords are important for keyword-based search
Rank2:Keyword-Based search relies on sparse embeddings
Rank3:Document analysis involves extracting keywords
Rank4:This is a list which is containing sample documents


In [ ]:
preprocess_query

'keywordbased search'

In [ ]:
documents_embeddings=np.array([
    [0.634,0.234,0.867,0.042,0.249],
    [0.123,0.456,0.789,0.321,0.654],
    [0.987,0.654,0.321,0.123,0.456]
])

In [ ]:
query_embedding=np.array([[0.789,0.321,0.654,0.987,0.123]])

In [ ]:
similarities = cosine_similarity(documents_embeddings,query_embedding)
similarities

array([[0.73558979],
       [0.67357898],
       [0.71517305]])

In [ ]:
rank_indices=np.argsort(similarities,axis=0)[::-1].flatten()

In [ ]:
rank_indices

array([0, 2, 1])

In [ ]:
for i,idx in enumerate(rank_indices):
  print(f"Rank{i+1}:Document:{idx+1}")

Rank1:Document:1
Rank2:Document:3
Rank3:Document:2


In [ ]:
doc_path="/content/Nuacem.pdf"

In [ ]:
!pip install pypdf langchain_community

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 45.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 53.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 408.7/408.7 kB 31.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 82.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 3.7 MB/s eta 0:00:00
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 2.0.36
    Uninstalling SQLAlchemy-2.0.36:
      Successfully uninstalled SQLAlchemy-2.0.36
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 0.3.13
    Uninstalling langchain-core-0.3.13:
      Successfully uninstalled langchain-core-0.3.13
  Attempting uninstall: langchain
    Found existing installation: langchain 0.3.4
    Uninstalling langchain-0.3.4:
      Successfully uninstalled langchain-0.3.4


In [ ]:
from langchain_community.document_loaders import PyPDFLoader

In [ ]:
loader = PyPDFLoader(doc_path)

In [ ]:
loader.load()

[Document(metadata={'source': '/content/Nuacem.pdf', 'page': 0}, page_content="Nuacem Pla tf orm Ov er vie w \n NuacemAIisaConversationalAI-PoweredCustomerEngagementPlatformthatcanamplifycustomerexperienceonText,Voice&Videochannels.WithourIntelligentCXtechnologysolutions,enterprisescandeliveranexceptionalconversationalexperiencetocustomers&automatebusinesscommunications.WeareexpertsincreatingabettercustomerexperienceforanyenterpriseviaConversationalAI.Weprovidecustomerswithend-to-endsupport–fromtheinitialrequirementstotheoperationoftheinnovativesolution–andensuretheycangeteverything“fromasinglesource.”Ourcustomersbenefitfromauniquecombinationofin-depthAIknowledgeandextensiveexperienceincustomerengagement,support,andexperienceforbusinessapplications.\nConnectwithyourclientsattheirmomentofneedwithNuacemAI’sCustomerEngagementSolution.OurConversationalAItechnologyimprovesyourcustomers’experiencebystreamliningserviceandengagementinreal-time …atanytime!\nN e x t G e n e r a t i o n C o n v e

In [ ]:
docs=loader.load()

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [ ]:
text_splitter=RecursiveCharacterTextSplitter(chunk_size=200,chunk_overlap=30)

In [ ]:
chunks = text_splitter.split_documents(docs)

In [ ]:
chunks

[Document(metadata={'source': '/content/Nuacem.pdf', 'page': 0}, page_content='Nuacem Pla tf orm Ov er vie w'),
 Document(metadata={'source': '/content/Nuacem.pdf', 'page': 0}, page_content='NuacemAIisaConversationalAI-PoweredCustomerEngagementPlatformthatcanamplifycustomerexperienceonText,Voice&Videochannels.WithourIntelligentCXtechnologysolutions,enterprisescandeliveranexceptionalconve'),
 Document(metadata={'source': '/content/Nuacem.pdf', 'page': 0}, page_content='escandeliveranexceptionalconversationalexperiencetocustomers&automatebusinesscommunications.WeareexpertsincreatingabettercustomerexperienceforanyenterpriseviaConversationalAI.Weprovidecustomerswithend'),
 Document(metadata={'source': '/content/Nuacem.pdf', 'page': 0}, page_content='alAI.Weprovidecustomerswithend-to-endsupport–fromtheinitialrequirementstotheoperationoftheinnovativesolution–andensuretheycangeteverything“fromasinglesource.”Ourcustomersbenefitfromauniquecombinationo'),
 Document(metadata={'source': '/content/

In [ ]:
from langchain.embeddings import HuggingFaceInferenceAPIEmbeddings

In [ ]:
from google.colab import userdata

In [ ]:
HF_token=userdata.get('HF_TOKEN')

In [ ]:
embeddings = HuggingFaceInferenceAPIEmbeddings(api_key=HF_token,model_name="BAAI/bge-base-en-v1.5")

In [ ]:
!pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 2.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.5/615.5 kB 16.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 53.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.8/273.8 kB 14.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.7/94.7 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 60.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.2/93.2 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 69.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.2/159.2 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.3/64.3 kB 5.7 MB/s eta 0:00:

In [ ]:
from langchain.vectorstores import Chroma

In [ ]:
vector_store=Chroma.from_documents(chunks,embeddings)

In [ ]:
vectorstore_retriever=vector_store.as_retriever(search_kwargs={"k":3})

In [ ]:
vectorstore_retriever

VectorStoreRetriever(tags=['Chroma', 'HuggingFaceInferenceAPIEmbeddings'], vectorstore=<langchain_community.vectorstores.chroma.Chroma object at 0x7dadcea94a30>, search_kwargs={'k': 3})

In [ ]:
!pip install rank_bm25

In [ ]:
from langchain.retrievers import BM25Retriever,EnsembleRetriever

In [ ]:
keyword_retriever=BM25Retriever.from_documents(chunks)

In [ ]:
keyword_retriever.k=3

In [ ]:
ble_retriever=EnsembleRetriever(retrievers=[vectorstore_retriever,keyword_retriever],weight=[0.3,0.7])

In [ ]:
model_name="HuggingFaceH4/zephyr-7b-beta"

In [ ]:
!pip install bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 MB 6.2 MB/s eta 0:00:00


In [ ]:
!pip install accelerate

In [ ]:
import torch
from transformers import (AutoModelForCausalLM,AutoTokenizer,BitsAndBytesConfig,pipeline)
from langchain import HuggingFacePipeline

In [ ]:
#Loading in 4bit quantized model
def load_quantize_model(model_name:str):
  """
  model name is the name of the model
  """
  bnb_config=BitsAndBytesConfig(
      load_in_4bit=True,
      bnb_4bit_quant_type="nf4",
      bnb_4bit_use_double_quant=True,
      bnb_4bit_compute_dtype=torch.bfloat16,
  )
  model=AutoModelForCausalLM.from_pretrained(
      model_name,
      torch_dtype=torch.bfloat16,
      quantization_config=bnb_config,
  )
  return model

In [ ]:
#initialize tokenizer
def initialize_tokenizer(model_name:str):
  "Model name for loading tokenizer"
  tokenizer=AutoTokenizer.from_pretrained(
      model_name,
      return_token_type_ids=False,)
  tokenizer.bos_token_id=1
  return tokenizer

In [ ]:
tokenizer=initialize_tokenizer(model_name)

tokenizer_config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

In [ ]:
model = load_quantize_model(model_name)

config.json:   0%|          | 0.00/638 [00:00<?, ?B/s]

`low_cpu_mem_usage` was None, now set to True since model is quantized.


model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

model-00001-of-00008.safetensors:   0%|          | 0.00/1.89G [00:00<?, ?B/s]

model-00002-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00003-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00004-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00005-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00006-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00007-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00008-of-00008.safetensors:   0%|          | 0.00/816M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    use_cache=True,
    device_map="auto",
    max_length=2048,
    do_sample=True,
    top_k=5,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.pad_token_id
)

In [ ]:
llm=HuggingFacePipeline(pipeline=pipeline)

<ipython-input-67-2654db8a482e>:1: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFacePipeline``.
  llm=HuggingFacePipeline(pipeline=pipeline)


In [ ]:
from langchain.chains import RetrievalQA

In [ ]:
normal_chain=RetrievalQA.from_chain_type(
    llm=llm,chain_type="stuff",retriever=vectorstore_retriever
)

In [ ]:
hubrid_chain=RetrievalQA.from_chain_type(
    llm=llm,chain_type="stuff",retriever=ble_retriever
)

In [ ]:
response=normal_chain.invoke("What is the summary?")

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [ ]:
response

{'query': 'What is the summary?',
 'result': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\ntimentandConversationalAnalytics❖IntegratedPlatform–OnePlatformforTextandVoice\n\n1 . C o n v e r s a t i o n a l A u t o m a t i o n\n\n2 . A u g m e n t e d H u m a n I n t e l l i g e n c e\n\nQuestion: What is the summary?\nHelpful Answer: The first text provides a brief overview of Timent and Conversational Analytics, highlighting the key features of their integrated platform for text and voice analysis. The second text touches on the topic of automated intelligence for humans, implying that this technology can enhance human intelligence and decision-making capabilities."}

In [ ]:
print(response.get('result'))

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

timentandConversationalAnalytics❖IntegratedPlatform–OnePlatformforTextandVoice

1 . C o n v e r s a t i o n a l A u t o m a t i o n

2 . A u g m e n t e d H u m a n I n t e l l i g e n c e

Question: What is the summary?
Helpful Answer: The first text provides a brief overview of Timent and Conversational Analytics, highlighting the key features of their integrated platform for text and voice analysis. The second text touches on the topic of automated intelligence for humans, implying that this technology can enhance human intelligence and decision-making capabilities.


In [ ]:
response1=hubrid_chain.invoke("What is the summary?")

In [ ]:
print(response1.get('result'))

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

timentandConversationalAnalytics❖IntegratedPlatform–OnePlatformforTextandVoice

C h a n n e l s s u p p o r t e d : 
 1. WhatsApp2. Website3. Facebook4. Instagram
C h a n n e l s N o t S u p p o r t e d : 1. MobileApps2. Viber

1 . C o n v e r s a t i o n a l A u t o m a t i o n

ionTheplatformprovidesoutoftheboxcapabilitiestoconnectwithcustomersacrossmultiplechannelslikeSocialMedia,Web,MessagingChannels,etc.viatext,voiceandvideowithplatformsupportingmorethan56nativelanguages.

2 . A u g m e n t e d H u m a n I n t e l l i g e n c e

r,design,training,testing,andimplementationofConversationalAutomationforanychannelinanyenvironmenttosuittheaudience.c.

Question: What is the summary?
Helpful Answer: The given context discusses different channels for customer interaction, including WhatsApp, website, Facebook, Instagram, mobile